freakout
% dont excecute me! >:O

analwin_dflt_1024  = blackmanharris(1024, 'periodic'); 
synthwin_dflt_1024 = hamming(1024, 'periodic');
hop_dflt_1024 = 1024/8

hop_dflt_256 = 256/8
analwin_dflt_256  = blackmanharris(256, 'periodic'); 
synthwin_dflt_256 = hamming(256, 'periodic');

analwin_dflt_32  = blackmanharris(32, 'periodic'); 
synthwin_dflt_32 = hamming(32, 'periodic');
hop_dflt_32 = 32/8

analwin_kaiserNoPR_1024 = kaiser(1024);
synthwin_kaiserNoPR_1024 = kaiser(1024);
hop_kaiserNoPR_1024 = 1024/4;

analwin_bhHamNoPR_1024  = blackmanharris(1024, 'periodic'); 
synthwin_bhHamNoPR_1024 = hamming(1024, 'periodic');
hop_bhHamNoPR_1024      = 1024/2 

testdefs = {
% original POC - canary
    "eNorm_source_sep_orig",                                                                           ...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_euclidian_norm(V,W,H, 0.001, 100000, 0),                                          ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*1, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*1, Fs),            ...
        99;

% a huge timesave - convergence % tests
% MAKE SURE THERES REASONABLY COMPLEX TESTCASES
    "convergence_thresh:0.01%",                                                                ...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_euclidian(V,W,H, 0.01 100000, 0),                                              ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),            ...
        99;

    "convergence_thresh:0.1%",                                                                ...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_euclidian(V,W,H, 0.001, 100000, 0),                                              ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),            ...
        99;

    "convergence_thresh:1%",                                                                ...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_euclidian(V,W,H, 0.01, 100000, 0),                                              ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),            ...
        99;

    "convergence_thresh:5%",                                                                ...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_euclidian(V,W,H, 0.05, 100000, 0),                                              ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),            ...
        99;

% different NMF update steps 
    "NMF_update_steps:euclidian",                                                                ...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_euclidian(V,W,H, 0.001, 100000, 0),                                              ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),            ...
        99;


    "NMF_update_steps:euclidian_norm",                                                           ...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_euclidian_norm(V,W,H, 0.01 100000, 0),                                         ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),            ...
        99;


    "NMF_update_steps:IS_divergence",                                                            ...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),            ...
        99;

    "NMF_update_steps:KL_divergence",                                                            ...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_kl(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),            ...
        99;

% different fft padding ratio
    "fft_zeropadding:pad_1x_wlen_1024",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01, 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*1, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),            ...
        99;

    "fft_zeropadding:pad_2x_wlen_1024",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01, 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*2, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),            ...
        99;

    "fft_zeropadding:pad_8x_wlen_1024",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01, 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),            ...
        99;

    "fft_zeropadding:pad_1x_wlen_256",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01, 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_256, hop_dflt_256, 256*1, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_256, synthwin_dflt_256, hop_dflt_256, 256*8, Fs),            ...
        99;


    "fft_zeropadding:pad_8x_wlen_256",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_256, hop_dflt_256, 256*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_256, synthwin_dflt_256, hop_dflt_256, 256*8, Fs),            ...
        99;

    "fft_zeropadding:pad_16x_wlen_256",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_256, hop_dflt_256, 256*16, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_256, synthwin_dflt_256, hop_dflt_256, 256*8, Fs),            ...
        99;

    "fft_zeropadding:pad_1x_wlen_32",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_32, hop_dflt_32, 32*1, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_32, synthwin_dflt_32, hop_dflt_32, 32*8, Fs),            ...
        99;

    "fft_zeropadding:pad_2x_wlen_32",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_32, hop_dflt_32, 32*2, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_32, synthwin_dflt_32, hop_dflt_32, 32*8, Fs),            ...
        99;

    "fft_zeropadding:pad_8x_wlen_32",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_32, hop_dflt_32, 32*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_32, synthwin_dflt_32, hop_dflt_32, 32*8, Fs),            ...
        99;

    "fft_zeropadding:pad_16x_wlen_32",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_32, hop_dflt_32, 32*16, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_32, synthwin_dflt_32, hop_dflt_32, 32*8, Fs),            ...
        99;

% Reconstruction
    "reconstruction:keepPhases_PR",                                                       ...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),            ...
        99;

    "reconstruction:keepPhases_noPR_kaiser",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_kaiserNoPR_1024, hop_kaiserNoPR_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_kaiserNoPR_1024, synthwin_kaiserNoPR_1024, hop_kaiserNoPR_1024, 1024*8, Fs),            ...
        99;

    "reconstruction:keepPhases_noPR_bhHam",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_bhHamNoPr_1024, hop_bhHamNoPr_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_keepPhase(orig_spect, W, H,                            ...
            analwin_bhHamNoPr_1024, synthwin_bhHamNoPr_1024, hop_bhHamNoPr_1024, 1024*8, Fs),            ...
        99;

    "reconstruction:noPhases_PR",                                                       ...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_noPhase(orig_spect, W, H,                            ...
            analwin_dflt_1024, synthwin_dflt_1024, hop_dflt_1024, 1024*8, Fs),            ...
        99;

    "reconstruction:noPhases_noPR_kaiser",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_kaiserNoPR_1024, hop_kaiserNoPR_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_noPhase(orig_spect, W, H,                            ...
            analwin_kaiserNoPR_1024, synthwin_kaiserNoPR_1024, hop_kaiserNoPR_1024, 1024*8, Fs),            ...
        99;

    "reconstruction:noPhases_noPR_bhHam",...
        @(freqBins, timeBins, K) nss_init_rand(freqBins, timeBins, K, 10),                             ...
        @(V,W,H) nss_is(V,W,H, 0.01 100000, 0),                                                     ...
        @(audio_vec, Fs) stft(audio_vec, analwin_bhHamNoPr_1024, hop_bhHamNoPr_1024, 1024*8, Fs),   ...
        @(orig_spect, W, H, Fs) nss_reconstruct_noPhase(orig_spect, W, H,                            ...
            analwin_bhHamNoPr_1024, synthwin_bhHamNoPr_1024, hop_bhHamNoPr_1024, 1024*8, Fs),            ...
        99;
};