function si = spectInfo_tuned
    % returns the best-performing spectInfo found during testing
    % no input arguments
    % note - parameters specific to a given audio file (e.g. fs) are not provided

    wlen = 1024;
    si = struct( ... 
        "wlen"         , wlen, ... 
        "nfft"         , wlen * 4, ...
        "hop"          , 256, ... 
        "analwin"      , blackmanharris(wlen, 'periodic'), ...
        "synthwin"     , hamming(wlen, 'periodic'), ...
        "max_freq_bins", floor(400 * wlen/1024) ...
    );
end